import type { GoalTemplate } from '@lyfestack/shared';
import { TaskType } from '@lyfestack/shared';

export const careerTemplate: GoalTemplate = {
  id: 'career_development',
  name: 'Career Development',
  description: 'Advance professionally — earn a promotion, land a new role, or build a marketable skill.',
  category: 'career',
  durationDays: 90,
  diagnosticQuestions: [
    {
      id: 'cd_objective',
      text: 'What is your primary career objective?',
      type: 'select',
      options: ['Get promoted at current job', 'Switch to a new company', 'Transition to a new field', 'Build a specific skill', 'Start freelancing or consulting', 'Launch a side project'],
      required: true,
    },
    {
      id: 'cd_timeline',
      text: 'What is your target timeline?',
      type: 'select',
      options: ['Within 3 months', '3–6 months', '6–12 months', '1–2 years'],
      required: true,
    },
    {
      id: 'cd_skill_gaps',
      text: 'Which areas need the most development? (select all that apply)',
      type: 'multiselect',
      options: ['Technical skills', 'Leadership & management', 'Communication & presentation', 'Networking', 'Personal brand / visibility', 'Portfolio / track record'],
      required: false,
    },
    {
      id: 'cd_networking_comfort',
      text: 'How comfortable are you with professional networking?',
      type: 'scale',
      min: 1,
      max: 10,
      required: true,
    },
    {
      id: 'cd_weekly_hours',
      text: 'Hours per week you can invest in career development (outside work hours)?',
      type: 'scale',
      min: 1,
      max: 20,
      required: true,
    },
  ],
  milestoneTemplates: [
    {
      id: 'cd_m1',
      title: 'Foundation & clarity',
      description: 'Define your target role, update materials, and identify gaps.',
      dayOffset: 14,
      successCriteria: ['Target role / company list defined', 'CV and LinkedIn updated', 'Skill gap list created with learning plan'],
    },
    {
      id: 'cd_m2',
      title: 'Skill-building momentum',
      description: 'Consistently invest in learning and begin building visibility.',
      dayOffset: 30,
      successCriteria: ['One course or certification started', '5+ meaningful professional connections made', 'One piece of public content published'],
    },
    {
      id: 'cd_m3',
      title: 'Active pursuit',
      description: 'Applications, conversations, or internal advocacy underway.',
      dayOffset: 60,
      successCriteria: ['5+ applications sent OR promotion conversation held', 'At least one informational interview completed', 'Skill completion or project demo ready'],
    },
    {
      id: 'cd_m4',
      title: 'Outcome achieved or pipeline built',
      description: 'Either land the opportunity or have a clear pipeline to continue.',
      dayOffset: 90,
      successCriteria: ['Offer received or promotion agreed OR concrete next steps identified', 'Portfolio / evidence of new skills complete', 'Next career milestone defined'],
    },
  ],
  suggestedActions: [
    {
      id: 'cd_a1',
      title: 'Daily skill learning block',
      description: 'Dedicate focused time to courses, reading, or practice in your skill gap area.',
      type: TaskType.HABIT,
      frequency: 'daily',
      durationMinutes: 30,
    },
    {
      id: 'cd_a2',
      title: 'Reach out to one new contact',
      description: 'Send a personalised connection request or follow-up message.',
      type: TaskType.ACTION,
      frequency: 'weekly',
      durationMinutes: 20,
    },
    {
      id: 'cd_a3',
      title: 'Weekly progress review',
      description: 'Review applications sent, connections made, and skills gained.',
      type: TaskType.REFLECTION,
      frequency: 'weekly',
      durationMinutes: 20,
    },
    {
      id: 'cd_a4',
      title: 'Write one piece of content',
      description: 'Post an article, LinkedIn update, or share a learning on your platform.',
      type: TaskType.ACTION,
      frequency: 'weekly',
      durationMinutes: 45,
    },
    {
      id: 'cd_a5',
      title: 'Identify and apply for 2 opportunities',
      description: 'Research and submit targeted applications or internal expressions of interest.',
      type: TaskType.ACTION,
      frequency: 'weekly',
      durationMinutes: 60,
    },
  ],
  milestones: [],
  defaultTaskTypes: [],
};
