import type { GoalTemplate } from '@lyfestack/shared';
import { TaskType } from '@lyfestack/shared';

export const financialTemplate: GoalTemplate = {
  id: 'financial_freedom',
  name: 'Financial Freedom',
  description: 'Build real financial security — eliminate debt, grow savings, and start investing.',
  category: 'finance',
  durationDays: 90,
  diagnosticQuestions: [
    {
      id: 'ff_primary_goal',
      text: 'What is your top financial priority?',
      type: 'select',
      options: ['Build an emergency fund', 'Pay off debt', 'Save for a major purchase', 'Start investing', 'Increase income', 'Create a budget and stick to it'],
      required: true,
    },
    {
      id: 'ff_monthly_surplus',
      text: 'Roughly how much disposable income do you have each month after bills?',
      type: 'select',
      options: ['Barely breaking even', '$1–$200', '$200–$500', '$500–$1,000', '$1,000+'],
      required: true,
    },
    {
      id: 'ff_debt_types',
      text: 'Do you have any of the following debts? (select all that apply)',
      type: 'multiselect',
      options: ['Credit card debt', 'Student loans', 'Personal loans', 'Car loan', 'Medical debt', 'No significant debt'],
      required: false,
    },
    {
      id: 'ff_investing_experience',
      text: 'How familiar are you with investing?',
      type: 'scale',
      min: 1,
      max: 10,
      required: true,
    },
    {
      id: 'ff_budget_in_place',
      text: 'Do you currently track your spending?',
      type: 'select',
      options: ['No budget at all', 'Rough idea in my head', 'Spreadsheet or app', 'Detailed envelope / zero-based budget'],
      required: true,
    },
  ],
  milestoneTemplates: [
    {
      id: 'ff_m1',
      title: 'Financial clarity',
      description: 'Know exactly where your money goes and build your first budget.',
      dayOffset: 14,
      successCriteria: ['Net worth statement completed', 'Budget created and tracked for 2 weeks', 'Highest-interest debt identified'],
    },
    {
      id: 'ff_m2',
      title: 'Savings habit locked in',
      description: 'Automated savings running and first debt payment accelerated.',
      dayOffset: 30,
      successCriteria: ['Auto-transfer to savings set up', 'One unnecessary subscription cancelled', 'Extra debt payment made'],
    },
    {
      id: 'ff_m3',
      title: 'Progress visible',
      description: 'Measurable movement on debt or savings goal.',
      dayOffset: 60,
      successCriteria: ['Net savings or debt payoff ≥ target for 60 days', 'Emergency fund balance tracked', 'Investment account opened (if applicable)'],
    },
    {
      id: 'ff_m4',
      title: 'System self-sustaining',
      description: 'Financial habits are automatic and compounding.',
      dayOffset: 90,
      successCriteria: ['90-day goal hit (debt reduced or savings target reached)', 'Budget adhered to ≥ 80% of weeks', 'Next 90-day financial goal set'],
    },
  ],
  suggestedActions: [
    {
      id: 'ff_a1',
      title: 'Daily spending log',
      description: 'Record every transaction — even small ones. Awareness is the foundation.',
      type: TaskType.HABIT,
      frequency: 'daily',
      durationMinutes: 5,
    },
    {
      id: 'ff_a2',
      title: 'Weekly budget review',
      description: 'Compare actual spending to budget by category, adjust if needed.',
      type: TaskType.ACTION,
      frequency: 'weekly',
      durationMinutes: 20,
    },
    {
      id: 'ff_a3',
      title: 'Negotiate one bill or subscription',
      description: 'Call or cancel one service, switch provider, or ask for a better rate.',
      type: TaskType.ACTION,
      frequency: 'once',
      durationMinutes: 30,
    },
    {
      id: 'ff_a4',
      title: 'Set up automatic savings transfer',
      description: 'Automate a fixed amount to savings on payday before you can spend it.',
      type: TaskType.ACTION,
      frequency: 'once',
      durationMinutes: 20,
    },
    {
      id: 'ff_a5',
      title: 'Learn one financial concept per week',
      description: 'Read or watch content on compound interest, index funds, tax, etc.',
      type: TaskType.HABIT,
      frequency: 'weekly',
      durationMinutes: 30,
    },
  ],
  milestones: [],
  defaultTaskTypes: [],
};
