import type { GoalTemplate } from '@lyfestack/shared';
import { TaskType } from '@lyfestack/shared';

export const learningTemplate: GoalTemplate = {
  id: 'learning_growth',
  name: 'Learning & Growth',
  description: 'Master a new skill, complete a course, or build knowledge that opens new doors.',
  category: 'learning',
  durationDays: 90,
  diagnosticQuestions: [
    {
      id: 'lg_subject',
      text: 'What do you want to learn or master?',
      type: 'text',
      required: true,
    },
    {
      id: 'lg_motivation',
      text: 'Why do you want to learn this?',
      type: 'select',
      options: ['Career advancement', 'Personal passion / curiosity', 'Build a business or side project', 'Solve a specific problem', 'Creative expression', 'Academic requirement'],
      required: true,
    },
    {
      id: 'lg_current_level',
      text: 'What is your current level in this subject?',
      type: 'select',
      options: ['Complete beginner', 'Know the basics', 'Intermediate — want to deepen', 'Advanced — want mastery or specialisation'],
      required: true,
    },
    {
      id: 'lg_learning_style',
      text: 'How do you learn best? (select all that apply)',
      type: 'multiselect',
      options: ['Video courses', 'Books / reading', 'Hands-on projects', 'Structured curriculum (bootcamp / course)', 'Mentorship or teaching others', 'Community and peer learning'],
      required: false,
    },
    {
      id: 'lg_daily_minutes',
      text: 'How many minutes per day can you dedicate to learning?',
      type: 'scale',
      min: 15,
      max: 180,
      required: true,
    },
  ],
  milestoneTemplates: [
    {
      id: 'lg_m1',
      title: 'Learning path defined',
      description: 'Clear curriculum selected and first sessions completed.',
      dayOffset: 14,
      successCriteria: ['Learning resource(s) chosen and started', '10+ hours of study logged', 'Key concepts from Module 1 articulated in own words'],
    },
    {
      id: 'lg_m2',
      title: 'Momentum and application',
      description: 'Knowledge translated into practice through a real project or exercise.',
      dayOffset: 30,
      successCriteria: ['First hands-on project or exercise started', 'Study streak ≥ 20 of 30 days', 'One concept taught to someone else or written up'],
    },
    {
      id: 'lg_m3',
      title: 'Intermediate competence',
      description: 'Noticeably more capable — able to tackle problems independently.',
      dayOffset: 60,
      successCriteria: ['Midpoint assessment or practice project completed', 'Sought feedback from a mentor or peer', 'Learning portfolio / notes organised'],
    },
    {
      id: 'lg_m4',
      title: 'Goal-level proficiency',
      description: 'Course completed or skill demonstrated at the target level.',
      dayOffset: 90,
      successCriteria: ['Curriculum or course completed', 'Capstone project or portfolio piece finished', 'Next level goal or application of skill defined'],
    },
  ],
  suggestedActions: [
    {
      id: 'lg_a1',
      title: 'Daily deep learning session',
      description: 'Focused, distraction-free study block — phone on silent, one topic at a time.',
      type: TaskType.HABIT,
      frequency: 'daily',
      durationMinutes: 45,
    },
    {
      id: 'lg_a2',
      title: 'Summarise what you learned today',
      description: 'Write 3–5 bullets of what you learned in your own words before closing the books.',
      type: TaskType.REFLECTION,
      frequency: 'daily',
      durationMinutes: 10,
    },
    {
      id: 'lg_a3',
      title: 'Work on a practice project',
      description: 'Apply the week\'s learning to a real or simulated project.',
      type: TaskType.ACTION,
      frequency: 'weekly',
      durationMinutes: 90,
    },
    {
      id: 'lg_a4',
      title: 'Weekly learning review',
      description: 'Review what you covered, what confused you, and what to revisit.',
      type: TaskType.REFLECTION,
      frequency: 'weekly',
      durationMinutes: 20,
    },
    {
      id: 'lg_a5',
      title: 'Teach or share one thing',
      description: 'Explain a concept to a friend, write a post, or record a short video — teaching locks in learning.',
      type: TaskType.SOCIAL,
      frequency: 'weekly',
      durationMinutes: 30,
    },
  ],
  milestones: [],
  defaultTaskTypes: [],
};
