import type { GoalTemplate } from '@lyfestack/shared';
import { TaskType } from '@lyfestack/shared';

export const healthFitnessTemplate: GoalTemplate = {
  id: 'health_fitness',
  name: 'Health & Fitness',
  description: 'Build lasting physical health habits — movement, nutrition, sleep, and recovery.',
  category: 'health',
  durationDays: 90,
  diagnosticQuestions: [
    {
      id: 'hf_primary_goal',
      text: 'What is your primary fitness goal?',
      type: 'select',
      options: ['Lose weight', 'Build muscle', 'Improve endurance', 'Reduce stress', 'General health'],
      required: true,
    },
    {
      id: 'hf_current_activity',
      text: 'How active are you currently?',
      type: 'select',
      options: ['Sedentary (desk job, little movement)', 'Lightly active (1–2 workouts/week)', 'Moderately active (3–4 workouts/week)', 'Very active (5+ workouts/week)'],
      required: true,
    },
    {
      id: 'hf_barriers',
      text: 'What are your biggest barriers? (select all that apply)',
      type: 'multiselect',
      options: ['Lack of time', 'Low motivation', 'Injury or pain', 'No gym access', 'Poor diet habits', 'Sleep issues'],
      required: false,
    },
    {
      id: 'hf_available_time',
      text: 'How many minutes per day can you dedicate to fitness?',
      type: 'scale',
      min: 10,
      max: 120,
      required: true,
    },
    {
      id: 'hf_dietary_approach',
      text: 'Which dietary approach are you open to?',
      type: 'select',
      options: ['No restrictions', 'Calorie counting', 'Low carb / keto', 'Plant-based', 'Intermittent fasting', 'Just eating cleaner'],
      required: true,
    },
  ],
  milestoneTemplates: [
    {
      id: 'hf_m1',
      title: 'Establish the routine',
      description: 'Complete 14 workouts and log meals for 2 weeks.',
      dayOffset: 14,
      successCriteria: ['14 workouts logged', 'Sleep average ≥ 7 hours', 'Baseline measurements recorded'],
    },
    {
      id: 'hf_m2',
      title: 'Break through the plateau',
      description: 'Increase workout intensity and hit the 30-day mark.',
      dayOffset: 30,
      successCriteria: ['Workout duration or weight increased by 10%', '30-day streak started', 'Progress photo taken'],
    },
    {
      id: 'hf_m3',
      title: 'Compound the gains',
      description: 'Fitness is now a default behaviour, not a decision.',
      dayOffset: 60,
      successCriteria: ['Missed ≤ 2 scheduled workouts in 4 weeks', 'Energy levels self-rated ≥ 7/10', 'Body composition measured'],
    },
    {
      id: 'hf_m4',
      title: 'New baseline achieved',
      description: 'Complete the 90-day transformation and set the next target.',
      dayOffset: 90,
      successCriteria: ['All three prior milestones hit', 'Before/after comparison documented', 'Next 90-day goal defined'],
    },
  ],
  suggestedActions: [
    {
      id: 'hf_a1',
      title: 'Morning movement (30 min)',
      description: 'Walk, run, cycle, or gym session before the day pulls you away.',
      type: TaskType.HABIT,
      frequency: 'daily',
      durationMinutes: 30,
    },
    {
      id: 'hf_a2',
      title: 'Log meals',
      description: 'Track breakfast, lunch, and dinner in a journal or app.',
      type: TaskType.HABIT,
      frequency: 'daily',
      durationMinutes: 5,
    },
    {
      id: 'hf_a3',
      title: 'Weekly weigh-in & measurements',
      description: 'Record weight and key body measurements every Sunday morning.',
      type: TaskType.ACTION,
      frequency: 'weekly',
      durationMinutes: 10,
    },
    {
      id: 'hf_a4',
      title: 'Plan next week\'s workouts',
      description: 'Block workout sessions in your calendar before the week starts.',
      type: TaskType.ACTION,
      frequency: 'weekly',
      durationMinutes: 15,
    },
    {
      id: 'hf_a5',
      title: 'Evening wind-down routine',
      description: 'Phone off, dim lights, and stretch or meditate for 15 min before bed.',
      type: TaskType.HABIT,
      frequency: 'daily',
      durationMinutes: 15,
    },
  ],
  milestones: [],
  defaultTaskTypes: [],
};
