import type { GoalTemplate } from '@lyfestack/shared';
import { TaskType } from '@lyfestack/shared';

export const relationshipsTemplate: GoalTemplate = {
  id: 'relationships_social',
  name: 'Relationships & Social',
  description: 'Strengthen the connections that matter — deepen friendships, improve communication, or meet new people.',
  category: 'relationships',
  durationDays: 90,
  diagnosticQuestions: [
    {
      id: 'rs_focus',
      text: 'Which area of relationships do you most want to improve?',
      type: 'select',
      options: ['Romantic relationship (existing)', 'Dating and meeting new people', 'Close friendships', 'Family relationships', 'Professional network', 'Overall social confidence'],
      required: true,
    },
    {
      id: 'rs_current_state',
      text: 'How would you rate your current social wellbeing?',
      type: 'scale',
      min: 1,
      max: 10,
      required: true,
    },
    {
      id: 'rs_challenges',
      text: 'What are your biggest relationship challenges? (select all that apply)',
      type: 'multiselect',
      options: ['Social anxiety or shyness', 'Difficulty expressing feelings', 'Conflict resolution', 'Making time for people', 'Loneliness or isolation', 'Trust issues'],
      required: false,
    },
    {
      id: 'rs_social_energy',
      text: 'Are you more introverted or extroverted?',
      type: 'select',
      options: ['Strong introvert (socialising drains me)', 'Mostly introverted', 'Balanced ambivert', 'Mostly extroverted', 'Strong extrovert (socialising energises me)'],
      required: true,
    },
    {
      id: 'rs_weekly_social_time',
      text: 'Hours per week you are willing to invest in social activities?',
      type: 'scale',
      min: 1,
      max: 15,
      required: true,
    },
  ],
  milestoneTemplates: [
    {
      id: 'rs_m1',
      title: 'Map your relationships',
      description: 'Identify who matters most and where gaps exist.',
      dayOffset: 14,
      successCriteria: ['Relationship map created (close, occasional, new)', 'One meaningful conversation had', 'One recurring social commitment scheduled'],
    },
    {
      id: 'rs_m2',
      title: 'Active investment begins',
      description: 'Consistent actions to nurture and expand connections.',
      dayOffset: 30,
      successCriteria: ['Weekly check-in habit with one close person started', 'Attended one new social event or activity', 'One uncomfortable conversation or vulnerability shared'],
    },
    {
      id: 'rs_m3',
      title: 'Deepening and expansion',
      description: 'Relationships are noticeably stronger and social confidence up.',
      dayOffset: 60,
      successCriteria: ['Quality time with priority relationships ≥ 4× in 30 days', 'New connection made and followed up', 'Relationship satisfaction self-rated ≥ 6/10'],
    },
    {
      id: 'rs_m4',
      title: 'Thriving connections',
      description: 'Social wellbeing is a consistent part of your life architecture.',
      dayOffset: 90,
      successCriteria: ['Social wellbeing self-rated ≥ 7/10 (up from baseline)', 'Consistent social habits embedded in weekly routine', 'Next relationship goal defined'],
    },
  ],
  suggestedActions: [
    {
      id: 'rs_a1',
      title: 'Daily gratitude message',
      description: 'Send a short genuine message to someone you appreciate — no agenda.',
      type: TaskType.SOCIAL,
      frequency: 'daily',
      durationMinutes: 5,
    },
    {
      id: 'rs_a2',
      title: 'Weekly quality time',
      description: 'Spend meaningful time with someone important — phone down, present.',
      type: TaskType.SOCIAL,
      frequency: 'weekly',
      durationMinutes: 60,
    },
    {
      id: 'rs_a3',
      title: 'Attend one new social event',
      description: 'Go somewhere you might meet people with shared interests.',
      type: TaskType.ACTION,
      frequency: 'weekly',
      durationMinutes: 120,
    },
    {
      id: 'rs_a4',
      title: 'Relationship reflection',
      description: 'Journal on how your key relationships are evolving and what needs attention.',
      type: TaskType.REFLECTION,
      frequency: 'weekly',
      durationMinutes: 15,
    },
    {
      id: 'rs_a5',
      title: 'Practice active listening',
      description: 'In one conversation today, focus entirely on the other person without steering.',
      type: TaskType.HABIT,
      frequency: 'daily',
      durationMinutes: 0,
    },
  ],
  milestones: [],
  defaultTaskTypes: [],
};
