import { agentOrchestrator } from '../agents/AgentOrchestrator';
import type { AgentRequest, AgentResponse } from '../agents/BaseAgent';
import { supabase } from '../lib/supabase';
import { v4 as uuidv4 } from 'uuid';

export class AgentService {
  async execute(request: AgentRequest): Promise<AgentResponse> {
    const response = await agentOrchestrator.dispatch(request);

    // Persist agent action for audit trail
    await supabase.from('agent_actions').insert({
      id: uuidv4(),
      user_id: request.userId,
      agent_role: response.agentRole,
      action: request.taskType,
      payload: request.payload,
      result: response.content,
      approval_state: 'PENDING',
      rationale: `Auto-generated by ${response.agentRole} agent`,
      created_at: new Date().toISOString(),
    });

    return response;
  }

  getAllowedActions() {
    return agentOrchestrator.getAllowedActions();
  }
}

export const agentService = new AgentService();
