export enum TaskStatus {
  PENDING = 'PENDING',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  SKIPPED = 'SKIPPED',
  FAILED = 'FAILED',
}

export enum TaskType {
  ACTION = 'ACTION',
  HABIT = 'HABIT',
  MILESTONE = 'MILESTONE',
  REFLECTION = 'REFLECTION',
  SOCIAL = 'SOCIAL',
}

export enum ApprovalState {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  MODIFIED = 'MODIFIED',
}
